# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21d4ea18df5db18d85816b61513e03e60857fea1d0598bfd9e3bbdf1a13f4f8470155a2b1785cd0a7033f236cc96e39e9c21887f49c24c9d7f2896e1fbfafe2d

test:
  secret_key_base: a1f0fdfb2d0efac7444dca17f4ddb0e1143a6eb32a420780a3c17e844058bf17955f63bccc51f5f703b5bdaa72b49596c3026b10567036f15de1e9532f2e525f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
